# Generated by Django 3.1.7 on 2022-05-26 17:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(choices=[('1', 'İnformasiya təhlükəsizliyinin əsasları'), ('2', 'Verilənlər bazası'), ('3', 'Korporativ informasiya sistemləri'), ('4', 'İnsidentlərin idarə olunması'), ('5', 'İnformasiya təhlükəsizliyində süni intellekt')], max_length=100, verbose_name='Fənnin adı')),
                ('result', models.IntegerField(default=0, verbose_name='İmtahanın nəticəsi')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Başlama tarixi')),
                ('last_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Bitmə tarixi')),
                ('participant_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İştirakçı adı')),
            ],
        ),
    ]
