# Generated by Django 3.1.7 on 2022-05-26 12:18

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email adresiniz')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Qoşulma tarixi')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Son giriş tarixi')),
                ('name', models.CharField(max_length=150, verbose_name='Adınız')),
                ('surname', models.CharField(max_length=150, verbose_name='Soyadınız')),
                ('group', models.CharField(choices=[('1', 'I - ci qrup'), ('2', 'II - ci qrup'), ('3', 'III - cü qrup'), ('4', 'IV - cü qrup')], max_length=100, verbose_name='Qrupunuz')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
